version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Digitalsegurogml2024!@159.223.152.198:5433/db"
      DB_HOST: "159.223.152.198"
      DB_PORT: 5433
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Digitalsegurogml2024!"
      DB_DATABASE: "db"
      SECRET_KEY: "secretKey"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REDIS_URL: "redis://localhost:6379"
      CORS_ORIGINS: "http://localhost:3000,http://localhost:5173,http://localhost:8080,https://gestor-custos.gmxindustrial.com.br"
      DEBUG: "True"
    restart: always
