"""add valor_previsto table with correct columns

Revision ID: 3d3f25a66958
Revises: 90c1ca56a41a
Create Date: 2025-09-19 08:23:44.424606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d3f25a66958'
down_revision = '90c1ca56a41a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar apenas a tabela valor_previsto
    op.create_table('valor_previsto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('servicos', sa.Text(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('qtd_mensal', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('duracao_meses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valor_previsto_id'), 'valor_previsto', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover apenas a tabela valor_previsto
    op.drop_index(op.f('ix_valor_previsto_id'), table_name='valor_previsto')
    op.drop_table('valor_previsto')
    # ### end Alembic commands ###