"""Initial migration

Revision ID: 90c1ca56a41a
Revises: 
Create Date: 2025-09-18 08:58:05.000825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90c1ca56a41a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_codigo'), 'cost_centers', ['codigo'], unique=True)
    op.create_index(op.f('ix_cost_centers_id'), 'cost_centers', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_cnpj'), 'suppliers', ['cnpj'], unique=True)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('attachment_type', sa.Enum('CERTIFICADO', 'COMPROVANTE_ENTREGA', 'RELATORIO_QUALIDADE', 'COTACAO', 'NOTA_FISCAL', 'ORDEM_COMPRA', 'PLANILHA_ORCAMENTO', 'OUTROS', name='attachmenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(), nullable=False),
    sa.Column('nome_projeto', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('tipo_contrato', sa.String(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('meta_reducao_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim_prevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_numero_contrato'), 'contracts', ['numero_contrato'], unique=True)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('codigo_item', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('centro_custo', sa.String(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('quantidade_prevista', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peso_previsto', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario_previsto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total_previsto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('horas_normais_previstas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('horas_extras_previstas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_previsto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('numero_oc', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_entrega_prevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_entrega_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('justificativa_escolha', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_numero_oc'), 'purchase_orders', ['numero_oc'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('numero_nf', sa.String(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_numero_nf'), 'invoices', ['numero_nf'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('budget_item_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('centro_custo', sa.String(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peso', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('horas_normais', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('horas_extras', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['budget_item_id'], ['budget_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('condicoes_pagamento', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('data_cotacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('centro_custo', sa.String(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peso', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('peso_divergente', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_divergente', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('justificativa_divergencia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.drop_table('activities')
    op.drop_table('macro_task')
    op.drop_table('effective')
    op.drop_table('workforce')
    op.drop_table('non_conformities')
    op.drop_index('IDX_0ac4404d41379e45131176d028', table_name='activity_collaborator')
    op.drop_index('IDX_27b82daf6f905ba31e61c095f0', table_name='activity_collaborator')
    op.drop_table('activity_collaborator')
    op.drop_table('process')
    op.drop_table('project')
    op.drop_table('teams')
    op.drop_table('activity_histories')
    op.drop_table('rnc_images')
    op.drop_table('service_orders')
    op.drop_table('value_per_position')
    op.drop_table('activity_image')
    op.drop_table('Worked_hours')
    op.drop_table('materials')
    op.drop_table('collaborators')
    op.drop_index('IDX_116d45a17b81e01f2bc0f45a03', table_name='activities_collaborators_collaborators')
    op.drop_index('IDX_b1c4fd41122e128b867d7e8963', table_name='activities_collaborators_collaborators')
    op.drop_table('activities_collaborators_collaborators')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('activities_collaborators_collaborators',
    sa.Column('activitiesId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collaboratorsId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activitiesId'], ['activities.id'], name='FK_116d45a17b81e01f2bc0f45a034', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collaboratorsId'], ['collaborators.id'], name='FK_b1c4fd41122e128b867d7e8963d'),
    sa.PrimaryKeyConstraint('activitiesId', 'collaboratorsId', name='PK_3a30f8429de7b6fff9b829fb1d1')
    )
    op.create_index('IDX_b1c4fd41122e128b867d7e8963', 'activities_collaborators_collaborators', ['collaboratorsId'], unique=False)
    op.create_index('IDX_116d45a17b81e01f2bc0f45a03', 'activities_collaborators_collaborators', ['activitiesId'], unique=False)
    op.create_table('collaborators',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('collaborators_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('teamId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['value_per_position.id'], name='FK_bdaf957510123411525b6aeeb2c'),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], name='FK_8e5f052b6fe8181b368c4e1c9ad', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='PK_f579a5df9d66287f400806ad875'),
    postgresql_ignore_search_path=False
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nonConformityId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('unidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preco', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nonConformityId'], ['non_conformities.id'], name='FK_3bdbe6cc23e8b6183fe026b0996', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_2fd1a93ecb222a28bef28663fa0')
    )
    op.create_table('Worked_hours',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Worked_hours_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('hoursWorked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('atividadeId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('colaboradorId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['atividadeId'], ['activities.id'], name='FK_e5aa98f1074c0aee345f447a9c5'),
    sa.ForeignKeyConstraint(['colaboradorId'], ['collaborators.id'], name='FK_004282c188e1aa995ee6bdbe784'),
    sa.PrimaryKeyConstraint('id', name='PK_f38a264f1525aa5e7dfbb0c6f3b')
    )
    op.create_table('activity_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('imageName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activityId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdById', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagePath', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activityId'], ['activities.id'], name='FK_501e83e7e5e90630c08e55eb6f0'),
    sa.ForeignKeyConstraint(['createdById'], ['users.id'], name='FK_c2ccd9d268e59a4ee3baddafbbf'),
    sa.PrimaryKeyConstraint('id', name='PK_63f626fcc351386a1a087695f22')
    )
    op.create_table('value_per_position',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('value_per_position_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_c629d8f79f053e5daed19c81ddd'),
    postgresql_ignore_search_path=False
    )
    op.create_table('service_orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('service_orders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('serviceOrderNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'Em andamento'::character varying"), autoincrement=False, nullable=False),
    sa.Column('startDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dueDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectNumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('projectIdId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assignedUserId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignedUserId'], ['users.id'], name='FK_d6eca55282b6b4e0c30dfddfd2c'),
    sa.ForeignKeyConstraint(['projectIdId'], ['project.id'], name='FK_ab966addceaa21c0a8e79e96046'),
    sa.PrimaryKeyConstraint('id', name='PK_914aa74962ee83b10614ea2095d'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rnc_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nonConformityId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nonConformityId'], ['non_conformities.id'], name='FK_8ee8557bdfa575a38d51bcb656a'),
    sa.PrimaryKeyConstraint('id', name='PK_3aa53ab62d477ffe1bd1be1dac7')
    )
    op.create_table('activity_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('activityId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changedById', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DayQuantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activities.id'], name='FK_5a6a25b2d000c595c6b6d625b12'),
    sa.ForeignKeyConstraint(['changedById'], ['users.id'], name='FK_9c248530bb05e8d0c2475cf92c2'),
    sa.PrimaryKeyConstraint('id', name='PK_46a1d88d8664780d4ef98b678eb')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teams_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_7e5523774a38b08a6236d322403'),
    postgresql_ignore_search_path=False
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('project_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('groupNumber', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('Fabrica', 'Obra', 'Mineradora', name='project_type_enum'), server_default=sa.text("'Fabrica'::project_type_enum"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_4d68b1358bb5b766d3e78f32f57'),
    postgresql_ignore_search_path=False
    )
    op.create_table('process',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('process_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_d5e3ab0f6df55ee74ca24967952'),
    postgresql_ignore_search_path=False
    )
    op.create_table('activity_collaborator',
    sa.Column('activitiesId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collaboratorsId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activitiesId'], ['activities.id'], name='FK_27b82daf6f905ba31e61c095f0c', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collaboratorsId'], ['collaborators.id'], name='FK_0ac4404d41379e45131176d0284'),
    sa.PrimaryKeyConstraint('activitiesId', 'collaboratorsId', name='PK_1f3e25b83a8d6d55cffca9f4bba')
    )
    op.create_index('IDX_27b82daf6f905ba31e61c095f0', 'activity_collaborator', ['activitiesId'], unique=False)
    op.create_index('IDX_0ac4404d41379e45131176d028', 'activity_collaborator', ['collaboratorsId'], unique=False)
    op.create_table('non_conformities',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dateOccurrence', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('correctiveAction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dateConclusion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('responsibleIdentification', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responsibleAction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responsibleRNC', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('serviceOrderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_28511f506a00bfeb02436037964'),
    sa.ForeignKeyConstraint(['responsibleAction'], ['collaborators.id'], name='FK_689344c4f294c90671622b17966'),
    sa.ForeignKeyConstraint(['responsibleIdentification'], ['collaborators.id'], name='FK_b6f2d5215a1dd9c45d492a338ff'),
    sa.ForeignKeyConstraint(['responsibleRNC'], ['collaborators.id'], name='FK_f771c3d92a199ff5849a811cc45'),
    sa.ForeignKeyConstraint(['serviceOrderId'], ['service_orders.id'], name='FK_7ff63a179c389ff1961e16be6ce'),
    sa.PrimaryKeyConstraint('id', name='PK_c89f2bca8b5acb75b63b9917ec4'),
    sa.UniqueConstraint('code', name='UQ_045c60dfaa3fcd26bb5e29ded7c', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('workforce',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('nonConformityId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('colaboradorId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('valueHour', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nonConformityId'], ['non_conformities.id'], name='FK_bd9e3e1c558076417a16b78525e', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_0284a6d21d24b590cb1ab29d684')
    )
    op.create_table('effective',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('shift', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('typeRegister', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_83e03631f0608ff73364637a2c8')
    )
    op.create_table('macro_task',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('macro_task_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_0415f7a96a839d115dd36188c14'),
    postgresql_ignore_search_path=False
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('Planejadas', 'Em execução', 'Concluídas', 'Paralizadas', name='activities_status_enum'), server_default=sa.text("'Planejadas'::activities_status_enum"), autoincrement=False, nullable=False),
    sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageDescription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fileUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fileDescription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timePerUnit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimatedTime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actualTime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('startDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('endDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pauseDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('totalTime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('originalStartDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('createdById', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serviceOrderId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cod_sequencial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completedQuantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('macroTask', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('process', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['createdById'], ['users.id'], name='FK_579056df0c92b0f6432e96b2048'),
    sa.ForeignKeyConstraint(['macroTask'], ['macro_task.id'], name='FK_0d6e0f1f336838ef0eaa4782363', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process'], ['process.id'], name='FK_72ee344736f15fa959c6064299f', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_e67cee936823900fc4d5f3feb14'),
    sa.ForeignKeyConstraint(['serviceOrderId'], ['service_orders.id'], name='FK_516182a2a4bde010f14de15b749'),
    sa.PrimaryKeyConstraint('id', name='PK_7f4004429f731ffb9c88eb486a8')
    )
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_invoices_numero_nf'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_purchase_orders_numero_oc'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_contracts_numero_contrato'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_cnpj'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_cost_centers_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_codigo'), table_name='cost_centers')
    op.drop_table('cost_centers')
    # ### end Alembic commands ###